### ISSUE TITLE
add success or failed message to search component

### ISSUE THREAD

**Issue by josuerojasrojas** [josuerojasrojas/wordsidontknow#45]
give a success message or failed message on search component when adding to a user's list

**Comment by PudparK** [comment]
Should the comment be viewable to the user? Or is this for error codes?

**Comment by josuerojasrojas** [comment]
I was imagining text would appear in the box 
Maybe at the bottom of it. 

If it’s success maybe in green it should say something like added successfully
If it’s an error maybe in red it should say something went wrong try again.
